# Generated by Django 5.2.7 on 2025-10-30 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_telegramuser_order_address_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='site_app.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
