# Generated by Django 5.2.7 on 2025-10-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_alter_order_options_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
